module.exports = {
  signUp: require('./signUp'),
  signIn: require('./signIn'),
  verifyOtp: require('./verifyOtp'),
  resendOtp: require('./resendOtp'),
  forgotPassword: require('./forgotPassword'),
  resetPassword: require('./resetPassword'),
  waStart: require('./waVerify').waStart,
  waStatus: require('./waVerify').waStatus,
  verifyEmail: require('./verifyEmail'),
  checkIsVerified: require('./checkIsVerified'),
  getMe: require('./getMe'),
  refreshToken: require('./refershToken'),
  logOut: require('./logOut'),
}
